### ISSUE TITLE
notworking

### ISSUE THREAD

**Issue by chandu1988** [cdowney/sf-messaging-client#4]
i am tring to connect but it is not getting any thing

**Comment by cdowney** [comment]
Hi @chandu1988, can you provide any more details about the issue you are seeing?

Can you provide an example I reproduce the issue with?
Do you have any logs?
What type of SF org are you connecting to?

**Comment by chandu1988** [comment]
i am using EMP Connector SF provided java code i am getting issues more ..
06-12-2019 12:18:12.287 [main] INFO  c.s.e.c.e.EmpconnectorApplication.logStartupProfileInfo - No active profile set, falling back to default profiles: default
06-12-2019 12:18:12.971 [main] INFO  c.s.e.c.e.EmpconnectorApplication.logStarted - Started EmpconnectorApplication in 1.101 seconds (JVM running for 1.527)
06-12-2019 12:18:12.997 [main] INFO  org.eclipse.jetty.util.log.initialized - Logging initialized @1551ms to org.eclipse.jetty.util.log.Slf4jLog
06-12-2019 12:18:13.303 [main] INFO  c.s.e.c.LoginHelper$LoginResponseParser.login - client start: ....
06-12-2019 12:18:14.470 [main] INFO  c.s.e.c.e.EmpconnectorApplication.subscriptionEventsSalesForce - token::
06-12-2019 12:18:14.471 [main] INFO  c.s.emp.connector.EmpConnector.connect - EmpConnector connecting
06-12-2019 12:18:15.102 [main] INFO  c.s.emp.connector.EmpConnector.subscribe - topic :/event/OutBound_PE__e
06-12-2019 12:18:15.102 [main] INFO  c.s.emp.connector.EmpConnector.subscribe - /event/OutBound_PE__eHI
06-12-2019 12:18:15.659 [main] INFO  c.s.e.c.e.EmpconnectorApplication.subscriptionEventsSalesForce - Subscribed: Subscription [/event/OutBound_PE__e:-1]
06-12-2019 12:18:15.660 [main] INFO  c.s.e.c.e.EmpconnectorApplication.main - ---------start----------
06-12-2019 18:23:37.327 [HttpClient@42eca56e-26] INFO  c.s.emp.connector.EmpConnector.stop - Disconnecting Bayeux Client in EmpConnector
06-12-2019 18:24:07.335 [HttpClient@42eca56e-26] ERROR c.s.emp.connector.EmpConnector.stop - Unable to stop HTTP transport[https://test.salesforce.com]
java.lang.RuntimeException: java.lang.InterruptedException
        at org.eclipse.jetty.util.component.ContainerLifeCycle.remove(ContainerLifeCycle.java:598)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.removeBean(ContainerLifeCycle.java:568)
        at org.eclipse.jetty.io.SelectorManager.doStop(SelectorManager.java:289)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.doStop(AbstractConnectorHttpClientTransport.java:70)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:266)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at com.salesforce.emp.connector.EmpConnector.stop(EmpConnector.java:155)
        at com.salesforce.emp.connector.EmpConnector$AuthFailureListener.onMessage(EmpConnector.java:344)
        at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyOnMessage(AbstractClientSession.java:597)
        at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyMessageListeners(AbstractClientSession.java:582)
        at org.cometd.common.AbstractClientSession.notifyListeners(AbstractClientSession.java:294)
        at org.cometd.common.AbstractClientSession.receive(AbstractClientSession.java:260)
        at org.cometd.client.BayeuxClient.failConnect(BayeuxClient.java:776)
        at org.cometd.client.BayeuxClient.processConnect(BayeuxClient.java:762)
        at org.cometd.client.BayeuxClient.processMessages(BayeuxClient.java:610)
        at org.cometd.client.BayeuxClient.access$3100(BayeuxClient.java:100)
        at org.cometd.client.BayeuxClient$MessageTransportListener.onMessages(BayeuxClient.java:1190)
        at org.cometd.client.transport.LongPollingTransport$2.onComplete(LongPollingTransport.java:236)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:196)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:188)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:470)
        at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:416)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:316)
        at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:599)
        at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1669)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1517)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:172)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:135)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1260)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.doStop(QueuedThreadPool.java:188)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.io.ManagedSelector.doStop(ManagedSelector.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.remove(ContainerLifeCycle.java:590)
        ... 51 common frames omitted
06-12-2019 18:24:07.336 [HttpClient@42eca56e-26] INFO  c.s.emp.connector.EmpConnector.connect - EmpConnector connecting
06-12-2019 18:24:07.337 [HttpClient@42eca56e-26] WARN  o.e.j.util.thread.QueuedThreadPool.execute - QueuedThreadPool[HttpClient@42eca56e]@569cfc36{FAILED,8<=8<=200,i=0,q=9}[org.eclipse.jetty.util.thread.TryExecutor$$Lambda$169/366004251@7204defe] rejected org.eclipse.jetty.io.ManagedSelector$$Lambda$174/733957003@37065eda
06-12-2019 18:24:07.338 [HttpClient@42eca56e-26] ERROR c.s.emp.connector.EmpConnector.connect - Unable to start HTTP transport[https://test.salesforce.com]
java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.io.ManagedSelector$$Lambda$174/733957003@37065eda
        at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:440)
        at org.eclipse.jetty.io.SelectorManager.execute(SelectorManager.java:163)
        at org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:116)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:262)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.doStart(AbstractConnectorHttpClientTransport.java:64)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.client.HttpClient.doStart(HttpClient.java:244)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.salesforce.emp.connector.EmpConnector.connect(EmpConnector.java:263)
        at com.salesforce.emp.connector.EmpConnector.reconnect(EmpConnector.java:325)
        at com.salesforce.emp.connector.EmpConnector.access$1100(EmpConnector.java:31)
        at com.salesforce.emp.connector.EmpConnector$AuthFailureListener.onMessage(EmpConnector.java:345)
        at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyOnMessage(AbstractClientSession.java:597)
        at org.cometd.common.AbstractClientSession$AbstractSessionChannel.notifyMessageListeners(AbstractClientSession.java:582)
        at org.cometd.common.AbstractClientSession.notifyListeners(AbstractClientSession.java:294)
        at org.cometd.common.AbstractClientSession.receive(AbstractClientSession.java:260)
        at org.cometd.client.BayeuxClient.failConnect(BayeuxClient.java:776)
        at org.cometd.client.BayeuxClient.processConnect(BayeuxClient.java:762)
        at org.cometd.client.BayeuxClient.processMessages(BayeuxClient.java:610)
        at org.cometd.client.BayeuxClient.access$3100(BayeuxClient.java:100)
        at org.cometd.client.BayeuxClient$MessageTransportListener.onMessages(BayeuxClient.java:1190)
        at org.cometd.client.transport.LongPollingTransport$2.onComplete(LongPollingTransport.java:236)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:196)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:188)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:470)
        at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:416)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:316)
        at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:599)
        at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1669)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1517)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:172)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:135)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
06-12-2019 18:24:07.338 [HttpClient@42eca56e-26] INFO  c.s.emp.connector.EmpConnector.onMessage - reconect........

**Comment by chandu1988** [comment]
can u explain the code how it will work so that i am using user name password authentication and login url. u r implementing token based so how to covert user name password authentication

**Comment by cdowney** [comment]
The [ManagedAuthClient](https://github.com/cdowney/sf-messaging-client/blob/master/src/main/java/io/cdsoft/sf/messaging/internal/client/auth/ManagedAuthClient.java#L66) uses the [Oauth2 password grant type](https://oauth.net/2/grant-types/password/) to obtain an API token. You will need to provide all 5 pieces of information `username`, `password`, `security token`, `clientId/consumerKey`, and `clientSecret/consumerSecret`.  The security token is provided to you by Salesforce when you set your password. The clientId and clientSecret are created by [creating a connected app](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_defining_remote_access_applications.htm)

The `ManagedAuthClient.getAuthResponse()` could be updated to use `CLIENT_CREDENTIALS` grant type, and then only clientId and clientSecret would be required. There is no way to use username/password alone.

**Comment by chandu1988** [comment]
https://github.com/forcedotcom/EMP-Connector

i am using this authentication token based
For token requests: https://login.salesforce.com/services/oauth2/token

i am using above code for connecting sale-force and getting message event. but i am getting error reconnecting issues so that can you help me how to sort out issue

**Comment by chandu1988** [comment]
if u dont mind can please share u r mail id i will contact and resolve the issue.

**Comment by chandu1988** [comment]
public class Client {

    public static void main(String[] args) throws Exception {

        // Set up ConnectionConfig instance with your values
        ConnectionConfig config = new ConnectionConfig();
        config.setLoginUrl("");
        config.setClientId("");
        config.setClientSecret("");
        config.setUserName("");
        config.setPassword("");
        config.setSecurityToken("");

        // Create an instance of the MessagingClient
        MessagingClient client = new MessagingClient(config);

        // Start the client
        client.start();

        // Create a message consumer
        JsonEventConsumer consumer = message -> System.out.println("Received message: " + message);

        // Create a Platform Event Subscription
        // Param 1: The paltform event API name
        // Param 2: Replay events from (-2 = earliest, -1 = tip, or specific event ID)
        // Param 2: An instance of EventConsumer (Either JsonEventConsumer or MapEventConsumer)
        Subscription subscription = new PlatformEventSubscription("Some_Event__e", -1L, consumer);

        // Subscribe to the event
        client.addSubscription(subscription);
    }
}
i am testing this code but nothing i am not getting event not connecting sales force,

can u please explain how to run this and what is the flow of execution 

when i am run above code i am getting below message only: 
 
log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
-------------io.cdsoft.sf.messaging.api.client.MessagingClient@204f30ec
